// Package fail2ban provides functions for installing and configuring fail2ban.
package fail2ban

import (
	"fmt"
	"os"
	"os/exec"

	"github.com/net2share/go-corelib/osdetect"
)

// JailConfigPath is the path to the fail2ban jail configuration.
const JailConfigPath = "/etc/fail2ban/jail.d/sshtunnel.conf"

// jailContent contains the fail2ban jail configuration.
const jailContent = `# fail2ban jail for SSH tunnel server
# Generated by sshtun-user
#
# Protects against brute-force attacks on tunnel user accounts
# Bans IPs after repeated failed authentication attempts

[sshtunnel]
enabled = true
port = ssh
filter = sshd
# Use systemd journal on modern systems, fallback to log file
backend = auto
# Ban for 1 hour after 5 failures within 10 minutes
maxretry = 5
findtime = 10m
bantime = 1h
# Progressive ban: repeat offenders get longer bans
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 1w
# Action: ban IP via firewall (iptables/nftables auto-detected)
banaction = auto
`

// IsInstalled checks if fail2ban is installed.
func IsInstalled() bool {
	_, err := exec.LookPath("fail2ban-client")
	return err == nil
}

// Install installs fail2ban using the detected package manager.
func Install(osInfo *osdetect.OSInfo) error {
	if IsInstalled() {
		fmt.Println("fail2ban is already installed")
		return nil
	}

	fmt.Println("fail2ban not found, installing...")

	if osInfo == nil {
		return fmt.Errorf("OS info required for package installation")
	}

	if err := osInfo.InstallPackage("fail2ban"); err != nil {
		return fmt.Errorf("failed to install fail2ban: %w", err)
	}

	// Enable and start fail2ban service
	exec.Command("systemctl", "enable", "fail2ban").Run()
	exec.Command("systemctl", "start", "fail2ban").Run()

	fmt.Println("fail2ban installed and started")
	return nil
}

// Configure creates the fail2ban jail configuration.
func Configure() error {
	// Create jail.d directory if it doesn't exist
	if err := os.MkdirAll("/etc/fail2ban/jail.d", 0755); err != nil {
		return fmt.Errorf("failed to create jail.d directory: %w", err)
	}

	// Write jail configuration
	if err := os.WriteFile(JailConfigPath, []byte(jailContent), 0644); err != nil {
		return fmt.Errorf("failed to write jail config: %w", err)
	}

	return nil
}

// Reload reloads the fail2ban configuration.
func Reload() error {
	// Check if fail2ban is running
	if err := exec.Command("systemctl", "is-active", "--quiet", "fail2ban").Run(); err != nil {
		// Not running, start it
		fmt.Println("Starting fail2ban...")
		if err := exec.Command("systemctl", "start", "fail2ban").Run(); err != nil {
			return fmt.Errorf("failed to start fail2ban: %w", err)
		}
		return nil
	}

	// Running, reload using fail2ban-client
	fmt.Println("Reloading fail2ban...")
	if err := exec.Command("fail2ban-client", "reload").Run(); err != nil {
		// fail2ban-client reload can fail if service just started or jail config
		// was written after service start. Restart picks up all configs reliably.
		fmt.Println("Reload failed, restarting fail2ban...")
		if err := exec.Command("systemctl", "restart", "fail2ban").Run(); err != nil {
			return fmt.Errorf("failed to restart fail2ban: %w", err)
		}
	}
	return nil
}

// IsJailActive checks if the sshtunnel jail is active.
func IsJailActive() bool {
	err := exec.Command("fail2ban-client", "status", "sshtunnel").Run()
	return err == nil
}

// Remove removes the fail2ban jail configuration.
func Remove() error {
	return os.Remove(JailConfigPath)
}

// SetupWithFeedback installs, configures, and reloads fail2ban with user feedback.
func SetupWithFeedback(osInfo *osdetect.OSInfo) error {
	// Install if needed
	if err := Install(osInfo); err != nil {
		fmt.Printf("Warning: Could not install fail2ban: %v\n", err)
		return nil
	}

	// Configure
	if err := Configure(); err != nil {
		return err
	}

	// Reload
	if err := Reload(); err != nil {
		return err
	}

	// Verify jail is active
	if IsJailActive() {
		fmt.Println("fail2ban jail 'sshtunnel' is active")
		fmt.Println("  - Ban after: 5 failed attempts in 10 minutes")
		fmt.Println("  - Ban duration: 1 hour (doubles for repeat offenders, max 1 week)")
	} else {
		fmt.Println("Warning: fail2ban jail may not be active yet (will activate on next restart)")
	}

	return nil
}
